### ISSUE TITLE
Doesnt work at all in atom v1.12.3

### ISSUE THREAD

**Issue by rbecheras** [mupchrch/minimap-split-diff#5]
1. The menu doesnt appear in the package menu. But maybe it is normal ?
2. When toggling `Minimap: Toggle Split Diff`, nothin happen (not any notification for enabling/disabling)
3. After toggling (and the same after retoggling) on, in dev mod, no any class is add to the lines where it were git changes)

How can I investigate deeper ?

**Comment by mupchrch** [comment]
Hi @rbecheras, sorry if I'm misunderstanding your issue but this package complements the main [split-diff package](https://atom.io/packages/split-diff). Have you installed that? That package is what does all the highlighting/class adding. This `minimap-split-diff` package is just what allows those highlights to appear in the minimap on the right hand side of the editor.

> 2. When toggling Minimap: Toggle Split Diff, nothin happen (not any notification for enabling/disabling)

What that command does is turn off the `minimap-split-diff` plugin so the highlights won't appear in the minimap, nothing will occur if there aren't any highlights to begin with.

Let me know if I didn't understand your questions correctly! And I think you've brought up a good point, maybe `minimap-split-diff` should automatically download split-diff if the user doesn't have it.
